apiVersion: v1
kind: ConfigMap
metadata:
  name: learning-backend-config
  namespace: devops-learning
data:
  CORS_ORIGINS: http://localhost:5173,http://localhost:8088
  DATABASE_URL: postgresql+psycopg://learning:learning@learning-db:5432/learningdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-backend
  namespace: devops-learning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learning-backend
  template:
    metadata:
      labels:
        app: learning-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
      containers:
        - name: backend
          image: devops-learning-backend:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: learning-backend-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: learning-backend
  namespace: devops-learning
spec:
  type: ClusterIP
  selector:
    app: learning-backend
  ports:
    - port: 8000
      targetPort: 8000
