def card(front: str, back: str, card_type: str = "interview") -> dict[str, str]:
    return {"front": front, "back": back, "card_type": card_type}


EXPANDED_DEVOPS_CARDS = {
    "Docker - Foundations": [
        card("What is the Docker build context?", "The build context is the set of files sent to the Docker daemon for a build. Dockerfile COPY and ADD can only access files inside this context.", "concept"),
        card("Why can Docker builds become slow?", "Large build contexts, poor layer ordering, frequent dependency cache invalidation, and downloading dependencies every build commonly make Docker builds slow.", "interview"),
        card("What is the difference between COPY and ADD?", "COPY copies files from the build context. ADD can also fetch URLs and automatically extract local tar archives, so COPY is usually preferred for clarity.", "interview"),
        card("Why should application logs go to stdout/stderr in containers?", "Container runtimes collect stdout/stderr, making logs available through docker logs, Kubernetes logs, and centralized log collectors.", "interview"),
        card("Command: inspect a Docker image.", "docker image inspect IMAGE_NAME", "command"),
        card("Command: list Docker networks.", "docker network ls", "command"),
        card("Command: inspect a Docker volume.", "docker volume inspect VOLUME_NAME", "command"),
        card("What is a named volume?", "A named volume is Docker-managed persistent storage that survives container removal and can be reused by new containers.", "concept"),
        card("What is a bind mount?", "A bind mount maps a host path into a container. It is useful for development but can be less portable than named volumes.", "concept"),
        card("Why is Alpine not always the best base image?", "Alpine is small, but musl libc can cause compatibility issues. Distroless, slim Debian, or official runtime images may be safer depending on the app.", "interview"),
        card("What is a distroless image?", "A distroless image contains only the application and runtime dependencies, with no shell or package manager, reducing attack surface.", "concept"),
        card("Scenario: Docker build cannot find a file during COPY. What do you check?", "Check the build context path, .dockerignore, file spelling, Dockerfile location, and whether you run docker build from the intended directory.", "scenario"),
        card("Scenario: Container is healthy locally but unhealthy in Docker. What do you check?", "Check healthcheck command, exposed port vs internal port, startup time, environment variables, dependencies, and logs.", "scenario"),
        card("What does `docker compose up --build` do?", "It builds images if needed, creates networks/volumes/containers, and starts the Compose-defined services.", "command"),
        card("What does `docker compose down -v` do?", "It removes Compose containers, networks, and named volumes declared by the Compose project, destroying persisted database data.", "command"),
        card("Why pin image versions instead of using latest?", "Pinned versions improve repeatability and prevent unexpected behavior when upstream latest changes.", "interview"),
        card("What is an image digest?", "An immutable content-addressed identifier for an image, such as sha256:..., stronger than a mutable tag.", "concept"),
        card("How do you reduce Docker image size?", "Use multi-stage builds, small runtime bases, .dockerignore, avoid package caches, and copy only required artifacts.", "interview"),
        card("What is Docker Compose service discovery?", "Services on the same Compose network can reach each other by service name, such as backend connecting to db.", "concept"),
        card("Scenario: Port 8080 is already in use. What can you do?", "Stop the process using it or change the host port mapping, for example 8081:8080.", "scenario"),
    ],
    "Kubernetes - Core Objects": [
        card("What is a ReplicaSet?", "A ReplicaSet ensures a specified number of matching Pods are running. Deployments manage ReplicaSets during rollouts.", "concept"),
        card("What is a StatefulSet?", "A StatefulSet manages Pods that need stable identity, ordered startup, and stable storage, often used for stateful workloads.", "concept"),
        card("What is a DaemonSet?", "A DaemonSet runs a Pod on every matching node, commonly used for log agents, monitoring agents, or networking components.", "concept"),
        card("What is an Ingress?", "Ingress routes external HTTP/HTTPS traffic to Services, often with host/path rules and TLS termination.", "concept"),
        card("What is the difference between ClusterIP, NodePort, and LoadBalancer?", "ClusterIP is internal, NodePort exposes a port on nodes, and LoadBalancer provisions an external load balancer where supported.", "interview"),
        card("Command: check rollout status.", "kubectl rollout status deployment/NAME -n NAMESPACE", "command"),
        card("Command: rollback a deployment.", "kubectl rollout undo deployment/NAME -n NAMESPACE", "command"),
        card("Command: show cluster events sorted by time.", "kubectl get events -n NAMESPACE --sort-by=.lastTimestamp", "command"),
        card("What is a PersistentVolumeClaim?", "A PVC is a request for storage. Kubernetes binds it to a PersistentVolume provided by the cluster storage system.", "concept"),
        card("What is a StorageClass?", "A StorageClass defines how dynamic storage is provisioned, including backend type, reclaim policy, and parameters.", "concept"),
        card("What is RBAC in Kubernetes?", "RBAC controls API permissions using Roles, ClusterRoles, RoleBindings, and ClusterRoleBindings.", "concept"),
        card("What is a ServiceAccount?", "A ServiceAccount is an identity used by Pods to authenticate to the Kubernetes API or cloud integrations.", "concept"),
        card("What is a PodDisruptionBudget?", "A PDB limits voluntary disruptions so maintenance does not evict too many healthy Pods at once.", "interview"),
        card("What is HPA?", "HorizontalPodAutoscaler adjusts replica count based on metrics such as CPU, memory, or custom metrics.", "concept"),
        card("Scenario: Pod is Pending. What do you check?", "Check events, node capacity, resource requests, taints/tolerations, PVC binding, affinity rules, and scheduler messages.", "scenario"),
        card("Scenario: Readiness probe fails. What happens?", "The Pod stays running but is removed from Service endpoints, so it does not receive traffic until ready.", "scenario"),
        card("Scenario: Liveness probe fails repeatedly. What happens?", "Kubernetes restarts the container, which can lead to CrashLoopBackOff if the underlying issue remains.", "scenario"),
        card("Why should you avoid putting databases in Kubernetes for many production teams?", "Managed databases usually provide better backups, patching, failover, replication, and operational reliability.", "interview"),
    ],
    "Helm - Charts and Values": [
        card("What files are usually inside a Helm chart?", "Chart.yaml, values.yaml, templates/, and optional files such as _helpers.tpl, charts/, and README.md.", "concept"),
        card("What is Chart.yaml?", "Chart.yaml contains chart metadata such as name, version, appVersion, description, and chart type.", "concept"),
        card("What is appVersion in Helm?", "appVersion documents the application version packaged by the chart. Chart version and app version are related but separate.", "concept"),
        card("What is a Helm release?", "A release is an installed instance of a chart with a specific name, values, and revision history.", "concept"),
        card("Command: list Helm releases in all namespaces.", "helm list -A", "command"),
        card("Command: lint a Helm chart.", "helm lint ./chart", "command"),
        card("Command: show release history.", "helm history RELEASE_NAME -n NAMESPACE", "command"),
        card("How do Helm values support environments?", "Teams use different values files for dev, staging, and prod while reusing the same templates.", "interview"),
        card("Why should secrets be handled carefully in Helm?", "Values files can end up in Git or release history. Production secrets should use external secret tooling.", "interview"),
        card("What is _helpers.tpl?", "A template file commonly used for reusable names, labels, and helper functions across chart templates.", "concept"),
        card("What does `helm upgrade --install` mean?", "Install the release if it does not exist; otherwise upgrade the existing release.", "command"),
        card("What is the difference between `helm template` and `helm install`?", "`helm template` renders YAML locally. `helm install` sends resources to the Kubernetes cluster.", "interview"),
        card("Scenario: Values are not applied as expected. What do you check?", "Check the values file path, key names, indentation, default values, template references, and rendered output.", "scenario"),
        card("Scenario: Helm upgrade creates invalid Kubernetes YAML. How do you debug?", "Run helm template, helm lint, inspect rendered YAML, and use kubectl dry-run validation.", "scenario"),
        card("Why version Helm charts?", "Chart versions make releases traceable, rollback-friendly, and publishable to chart repositories.", "interview"),
        card("What is a chart dependency?", "A chart dependency lets one chart include another chart, for example an app chart depending on PostgreSQL.", "concept"),
        card("What is `helm pull` used for?", "It downloads a chart from a repository, optionally untarring it for inspection or customization.", "command"),
        card("What is `helm repo update` used for?", "It refreshes local chart repository indexes so Helm sees the latest available chart versions.", "command"),
        card("Why avoid too much logic in Helm templates?", "Complex template logic becomes hard to read, test, and troubleshoot. Keep charts predictable.", "interview"),
        card("What is a post-renderer in Helm?", "A post-renderer modifies rendered manifests before they are applied, often used with tools like Kustomize.", "concept"),
        card("What does `--atomic` do in Helm upgrade?", "It rolls back changes automatically if the upgrade fails, helping avoid partially failed releases.", "command"),
        card("What does `--wait` do in Helm?", "It waits for Kubernetes resources to become ready before marking the release successful.", "command"),
        card("Scenario: Helm rollback succeeds but app still fails. What next?", "Check logs, events, config values, image tags, database migrations, and whether external dependencies changed.", "scenario"),
    ],
    "CI/CD - GitHub Actions": [
        card("What is a workflow in GitHub Actions?", "A workflow is an automated process defined in YAML under .github/workflows and triggered by events like push or pull_request.", "concept"),
        card("What is a job in GitHub Actions?", "A job is a set of steps that run on the same runner. Jobs can run in parallel or depend on each other.", "concept"),
        card("What is a runner?", "A runner is the machine that executes workflow jobs, either GitHub-hosted or self-hosted.", "concept"),
        card("What does `needs` do in GitHub Actions?", "`needs` defines job dependencies and prevents a job from starting until required jobs succeed.", "command"),
        card("Why use dependency caching in CI?", "Caching reduces build time by reusing downloaded dependencies between workflow runs.", "interview"),
        card("Why should secrets not be printed in CI logs?", "Logs are often visible to many people and retained. Leaking secrets can compromise systems.", "interview"),
        card("What is a deployment environment in GitHub Actions?", "An environment can require approvals, store environment-specific secrets, and track deployments.", "concept"),
        card("What is the difference between artifact and cache?", "Artifacts preserve build outputs for later download. Caches speed up future runs by storing dependencies.", "interview"),
        card("Command concept: what does `docker build -t app:$GITHUB_SHA .` achieve?", "It tags the image with the exact commit SHA, making the image traceable to source code.", "concept"),
        card("What is a matrix build?", "A matrix runs the same job across combinations such as multiple OS versions, language versions, or configurations.", "concept"),
        card("Scenario: Docker build in CI cannot access a private registry. What do you check?", "Check registry login step, secrets, permissions, image name, network access, and whether the token has pull/push rights.", "scenario"),
        card("Scenario: CI is slow. What optimizations do you consider?", "Use caching, split jobs, avoid unnecessary installs, use smaller images, parallelize tests, and reduce Docker build context.", "scenario"),
        card("Why separate build and deploy stages?", "It creates a clear promotion path where the same tested artifact can be deployed to multiple environments.", "interview"),
        card("What is continuous delivery?", "Every change is automatically validated and kept deployable, but production deployment may still require approval.", "concept"),
        card("What is continuous deployment?", "Every validated change is automatically deployed to production without manual approval.", "concept"),
        card("Why use branch protection rules?", "They prevent unreviewed or failing code from being merged into important branches.", "interview"),
        card("What is a rollback strategy?", "A planned way to restore a previous working version, such as redeploying an older image tag or Helm revision.", "concept"),
        card("Why run security scans in CI?", "To catch known vulnerabilities, secret leaks, and risky dependencies before deployment.", "interview"),
        card("What is an ephemeral environment?", "A temporary environment created for a branch or pull request and destroyed after review/testing.", "concept"),
        card("Scenario: Deployment succeeds but users see errors. What pipeline data helps?", "Deployment time, image tag, commit SHA, config changes, migration logs, health checks, and rollout events.", "scenario"),
        card("Why is `latest` a poor production image tag?", "It is mutable, making deployments hard to reproduce, audit, and roll back.", "interview"),
        card("What is a manual approval gate?", "A required human approval step before continuing, often used before production deployment.", "concept"),
        card("Why publish test reports as artifacts?", "They help investigate failures without rerunning the pipeline and provide historical evidence.", "interview"),
    ],
    "Terraform - Basics": [
        card("What is Terraform drift?", "Drift occurs when real infrastructure differs from Terraform state/configuration, often due to manual changes.", "concept"),
        card("How do you detect Terraform drift?", "Run terraform plan and compare proposed changes against expected infrastructure.", "command"),
        card("What is a Terraform module?", "A module is a reusable group of Terraform resources with inputs and outputs.", "concept"),
        card("Why use modules?", "Modules reduce duplication, standardize infrastructure patterns, and make environments easier to manage.", "interview"),
        card("What is a Terraform variable?", "A variable is an input used to parameterize configuration, such as region, instance size, or environment name.", "concept"),
        card("What is a Terraform output?", "An output exposes useful values from a configuration, such as a load balancer DNS name.", "concept"),
        card("What is `terraform init`?", "It initializes providers, modules, and backend configuration for a working directory.", "command"),
        card("What is `terraform validate`?", "It checks whether Terraform configuration syntax and internal references are valid.", "command"),
        card("What is `terraform import`?", "It brings existing infrastructure under Terraform state management.", "command"),
        card("Why is state locking important?", "It prevents two users or pipelines from modifying the same state at the same time.", "interview"),
        card("What is a backend in Terraform?", "A backend defines where Terraform stores state, such as local files, S3, Azure Storage, or Terraform Cloud.", "concept"),
        card("Why avoid storing secrets directly in Terraform state?", "State can contain sensitive values in plain text, so it must be protected and secrets should be handled carefully.", "interview"),
        card("Scenario: Terraform apply fails halfway. What do you do?", "Inspect the error, check state, run plan again, verify created resources, and avoid manual deletion unless you understand state impact.", "scenario"),
        card("What is `lifecycle prevent_destroy`?", "A lifecycle rule that blocks Terraform from destroying a resource unless the rule is removed.", "concept"),
        card("What is `create_before_destroy`?", "A lifecycle rule that creates a replacement resource before destroying the old one, reducing downtime when supported.", "concept"),
        card("What is provider version pinning?", "Constraining provider versions to avoid unexpected behavior from automatic upgrades.", "interview"),
        card("What is the `.terraform.lock.hcl` file?", "It records selected provider versions and checksums for repeatable Terraform installs.", "concept"),
        card("Scenario: Terraform plan shows many unexpected changes. What do you check?", "Check provider versions, variables, workspace, state backend, manual drift, generated names, and module changes.", "scenario"),
        card("What is a workspace?", "A Terraform workspace is a separate state instance for the same configuration, often used carefully for environments.", "concept"),
        card("Why do many teams prefer separate environment folders over workspaces?", "Folders make environment differences explicit and reduce the risk of accidentally applying to the wrong workspace.", "interview"),
        card("What is `terraform taint` historically used for?", "It marked a resource for replacement, though modern Terraform prefers `-replace` during plan/apply.", "concept"),
        card("Command: force replacement of a resource.", "terraform apply -replace=RESOURCE_ADDRESS", "command"),
        card("Why review Terraform plans in pull requests?", "Infrastructure changes can be risky; reviewing plans helps catch destructive or unexpected changes before apply.", "interview"),
    ],
    "Monitoring - Prometheus and Grafana": [
        card("What is RED monitoring?", "RED tracks Rate, Errors, and Duration for request-driven services.", "concept"),
        card("What is USE monitoring?", "USE tracks Utilization, Saturation, and Errors for infrastructure resources.", "concept"),
        card("What is a Prometheus label?", "A label is a key-value pair attached to a metric, used for filtering and aggregation.", "concept"),
        card("Why can high-cardinality labels be dangerous?", "Too many unique label values can overload Prometheus storage and queries.", "interview"),
        card("What is a histogram metric?", "A histogram samples observations into buckets, commonly used for latency percentiles.", "concept"),
        card("What is a counter metric?", "A counter only increases and is used for totals like request count or error count.", "concept"),
        card("What is a gauge metric?", "A gauge can go up or down, such as current memory usage or active connections.", "concept"),
        card("What is Alertmanager?", "Alertmanager receives Prometheus alerts, deduplicates/groups them, and routes notifications.", "concept"),
        card("Why should alerts have runbooks?", "Runbooks tell on-call engineers what the alert means, how to investigate, and how to mitigate.", "interview"),
        card("Scenario: Alert says high 5xx rate. What do you check first?", "Check recent deployments, application logs, error traces, dependency health, database errors, and traffic changes.", "scenario"),
        card("Scenario: Memory usage keeps increasing. What could it indicate?", "A memory leak, cache growth, too many connections, bad workload size, or missing memory limits.", "scenario"),
        card("What is log aggregation?", "Collecting logs from many containers/nodes into a central searchable system.", "concept"),
        card("What is distributed tracing?", "Tracing follows a request across services to identify latency, errors, and dependency paths.", "concept"),
        card("What is OpenTelemetry?", "A vendor-neutral standard and toolkit for collecting traces, metrics, and logs.", "concept"),
        card("Why expose `/health` separately from `/metrics`?", "Health is for readiness/liveness checks. Metrics are for monitoring and analysis.", "interview"),
        card("What is an error budget?", "The allowed amount of unreliability within an SLO period, used to balance speed and reliability.", "concept"),
        card("What should a good dashboard show?", "User impact, request rate, latency, errors, saturation, dependency health, and recent deployment context.", "interview"),
        card("Scenario: CPU is high but latency is normal. Is it urgent?", "Not always. Investigate trend and saturation, but alerting should usually focus on user impact or nearing resource limits.", "scenario"),
        card("What is black-box monitoring?", "Monitoring from the outside like a user would, such as HTTP checks against public endpoints.", "concept"),
        card("What is white-box monitoring?", "Monitoring internal application metrics such as request duration, queue size, memory, and DB pool usage.", "concept"),
        card("Why include deployment markers in observability tools?", "They help correlate errors or latency changes with a specific release.", "interview"),
        card("What is MTTR?", "Mean Time To Recovery, a measure of how quickly a team restores service after incidents.", "concept"),
        card("What is an incident postmortem?", "A blameless review of what happened, impact, root causes, and follow-up actions after an incident.", "concept"),
    ],
    "Security - DevOps Hardening": [
        card("What is supply chain security?", "Protecting the software delivery chain: source, dependencies, build systems, images, registries, and deployments.", "concept"),
        card("What is SBOM?", "A Software Bill of Materials lists components and dependencies included in an application or image.", "concept"),
        card("Why sign container images?", "Signing helps verify image provenance and detect tampering before deployment.", "interview"),
        card("What is TLS termination?", "The point where encrypted HTTPS traffic is decrypted, often at an ingress controller or load balancer.", "concept"),
        card("What is mTLS?", "Mutual TLS where both client and server authenticate each other using certificates.", "concept"),
        card("What is secret rotation?", "Replacing secrets regularly or after suspected exposure to reduce compromise duration.", "concept"),
        card("What is the principle of defense in depth?", "Using multiple layers of controls so one failure does not fully compromise the system.", "interview"),
        card("What is a vulnerability CVE?", "A publicly known cybersecurity vulnerability with an identifier and severity information.", "concept"),
        card("Why avoid privileged containers?", "Privileged containers get broad host capabilities and greatly increase the blast radius of compromise.", "interview"),
        card("What is Pod Security Admission?", "A Kubernetes admission controller enforcing Pod Security Standards such as baseline or restricted.", "concept"),
        card("Scenario: A secret was committed to Git. What do you do?", "Rotate the secret immediately, remove it from active use, audit access, and clean repository history if needed.", "scenario"),
        card("Scenario: Image scan finds critical CVEs. What do you check?", "Check if the vulnerable package is present and exploitable, update base image/dependencies, rebuild, and rescan.", "scenario"),
        card("What is a security context in Kubernetes?", "Settings that define privilege and access control for Pods or containers, such as runAsNonRoot and capabilities.", "concept"),
        card("Why drop Linux capabilities?", "Most containers do not need them. Dropping capabilities reduces what a compromised process can do.", "interview"),
        card("What is egress control?", "Restricting outbound network traffic so workloads can only call approved destinations.", "concept"),
        card("What is ingress control?", "Restricting inbound traffic to a workload, often with NetworkPolicy, firewalls, or security groups.", "concept"),
        card("Why separate duties in CI/CD permissions?", "Build, deploy, and admin privileges should be separated to reduce risk from compromised tokens or users.", "interview"),
        card("What is OIDC in CI/CD?", "OpenID Connect lets CI jobs request short-lived cloud credentials instead of storing long-lived secrets.", "concept"),
        card("What is a short-lived credential?", "A credential that expires quickly, reducing damage if leaked.", "concept"),
        card("Why audit Kubernetes API access?", "Audit logs help detect suspicious activity, investigate incidents, and prove compliance.", "interview"),
        card("What is dependency pinning?", "Constraining dependency versions so builds are repeatable and changes are reviewed intentionally.", "concept"),
        card("Scenario: A Pod needs cloud permissions. What is safer than static keys?", "Use workload identity or IAM roles for service accounts, giving short-lived scoped credentials.", "scenario"),
        card("Why should production secrets not be visible to developers by default?", "Least privilege reduces accidental leaks and limits blast radius if a developer account is compromised.", "interview"),
    ],
}
